### ISSUE TITLE
Fresh install: Updatescript stuck in loop

### ISSUE THREAD

**Issue by oerkel47** [JarvyJ/HomeIntent#226]
Hi @JarvyJ and thanks for homeintent. I have tried it some months ago but have since paused my smart speaker projects. Now I got a pizero2 and wanted to give it another go. Seems as HomeIntent has since improved a lot - unfortunately I am struggling setting it up..

I did a fresh installation of HomeIntent via docker-compose. I tried to set things up in the Web-UI, but it doesn't seem to save anything. So I tried to figure out what's wrong.

In the log console I can see the update script running in a loop.
```
2021-12-15 18:24:10,143 INFO home_intent.updater Running update script for version: 2021.12.0
2021-12-15 18:24:12,857 INFO home_intent.rhasspy_api Trying to connect to Rhasspy at http://localhost:12101
2021-12-15 18:24:12,932 INFO root Using language: en
2021-12-15 18:24:12,952 INFO home_intent.updater Running update script for version: 2021.12.0
2021-12-15 18:24:15,686 INFO home_intent.rhasspy_api Trying to connect to Rhasspy at http://localhost:12101
```

Additionally, in the docker log I found:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/home_intent/__main__.py", line 120, in <module>
    main(logging_host)
  File "/usr/src/app/home_intent/__main__.py", line 51, in main
    home_intent.initialize()
  File "/usr/src/app/home_intent/home_intent.py", line 187, in initialize
    update_homeintent(self)
  File "/usr/src/app/home_intent/updater.py", line 59, in update_homeintent
    _perform_updates(update_scripts, home_intent)
  File "/usr/src/app/home_intent/updater.py", line 85, in _perform_updates
    script.run(home_intent)
  File "/usr/src/app/home_intent/updater.py", line 46, in run
    script.run(home_intent)
  File "/usr/src/app/home_intent/update_scripts/2021/2021-12-0.py", line 28, in run
    if home_intent.settings.home_assistant:
AttributeError: 'Settings' object has no attribute 'home_assistant'
2021-12-15 18:22:09,156 INFO exited: home_intent (exit status 1; not expected)
2021-12-15 18:22:10,164 INFO spawned: 'home_intent' with pid 1061
2021-12-15 18:22:11,169 INFO success: home_intent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
The log goes on and this was looping as well (as expected).

From the error this sounds as it would be expecting initialized settings for HomeAssistant which it can not find and I can not set.

**Comment by JarvyJ** [comment]
Ahh yes, thanks for submitting the logs!  You're right, it looks like it's expecting the settings object to have a home assistant section in it, which it doesn't on a new install.

It should be a quick fix to get it resolved, I'll get to it later today! I'll also look into setting up an integration test to catch this in the future.

If you need it working immediately, you could install the previous release, preform the setup, and then update. Or just wait a couple hours and I'll cut a new release!

Thanks for using it and reporting back!

**Comment by oerkel47** [comment]
Thanks for the quick reply!
I thought I could probably fix this by setting a config up manually in the appropriate folder, but this seemed report worthy.
I will check again tomorrow.

**Comment by JarvyJ** [comment]
Yes, setting it up manually would also fix it! I just pushed the changes to main. I'll test it out and cut a new release!

Thanks for reporting, there were actually a few issues with first boot. For now I'll manually verify before cutting new releases that a fresh install will still work. I'd love to get some automated testing around it, but that's a little down the line.

**Comment by JarvyJ** [comment]
Tested it out and cut the release! Thanks for the tip!

**Comment by oerkel47** [comment]
Thank you, the loop bug is fixed. Regarding the settings not saving (which resulted in the loop not stopping) I opened another issue.
