### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by nyok92** [JarvyJ/HomeIntent#426]
Hi ! I will try to translate to french.
I added too a PR for media_player entity control.
Great repo !
Thanks

**Comment by nyok92** [comment]
Hi JarvyJ,
PR request opened @JarvyJ 

https://github.com/JarvyJ/HomeIntent/pull/429

**Comment by JarvyJ** [comment]
Oh wow thank you! Love to see a new translation get added and the media controls I think were some of the last low hanging fruit to be added! I'll look over the code and merge in the PRs in the next couple of days and get ready for another release.

Thanks for the contribution, it's very much appreciated. I hope the docs and examples were helpful!

**Comment by nyok92** [comment]
Hello @JarvyJ 
There was some typo issues on my PR.
I resolved a few but i can't manage to get media_ player volume_set volume_level working correctly.
If i disable this in base_media_player.py and fr.py i still get the following error:

```
12/07/2022 17:44:13 INFO home_intent.rhasspy_api Trying to connect to Rhasspy at http://127.0.0.1:12101
12/07/2022 17:44:14 INFO root Using language: fr
12/07/2022 17:44:14 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.timer.base_timer...
12/07/2022 17:44:14 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:14 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.climate.base_climate...
12/07/2022 17:44:14 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:14 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.cover.base_cover...
12/07/2022 17:44:14 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:14 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.fan.base_fan...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.group.base_group...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.humidifier.base_humidifier...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.light.base_light...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.lock.base_lock...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.shopping_list.base_shopping_list...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.switch.base_switch...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.weather.base_weather...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.home_intent Verifying sentences' slots for home_intent.components.home_assistant.media_player.base_media_player...
12/07/2022 17:44:15 INFO home_intent.home_intent Sentences look good!
12/07/2022 17:44:15 INFO home_intent.updater No updates to perform this release!
12/07/2022 17:44:15 INFO home_intent.home_intent Externally Managed Setting enabled - skipping Rhasspy profile processing
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.timer.base_timer
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for timer_partial_time
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.climate.base_climate
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate_target_temperature_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate_target_temperature_range_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate_hvac_mode
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate_target_humidity_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate_preset_mode_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate_preset_mode
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for climate_aux_heat_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.cover.base_cover
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_open_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_close_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_set_position_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_stop_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_open_tilt_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_close_tilt_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_set_tilt_position_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for cover_positions
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.fan.base_fan
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for fan
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for fan_oscillate_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for fan_preset_mode_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for fan_preset_mode
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for fan_direction_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for fan_set_speed_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for fan_speed
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.group.base_group
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for group
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.humidifier.base_humidifier
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for humidifier
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for humidifier_mode
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.light.base_light
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for light
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for light_color
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for light_color_temperature
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.lock.base_lock
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for lock
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for lock_open_entity
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.shopping_list.base_shopping_list
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for shopping_list_item
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.switch.base_switch
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for switch
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.weather.base_weather
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for weather_day_of_week
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slots for home_intent.components.home_assistant.media_player.base_media_player
12/07/2022 17:44:15 INFO home_intent.home_intent Getting slot values for media_player
12/07/2022 17:44:15 INFO home_intent.home_intent Updating all slots in Rhasspy
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.timer.base_timer
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.climate.base_climate
12/07/2022 17:44:15 INFO home_intent.home_intent Running register func: <function Climate.handle_prefer_toggle at 0x7f9a8d4d08>
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.cover.base_cover
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.fan.base_fan
12/07/2022 17:44:15 INFO home_intent.home_intent Running register func: <function Fan.handle_prefer_toggle at 0x7f9a87b488>
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.group.base_group
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.humidifier.base_humidifier
12/07/2022 17:44:15 INFO home_intent.home_intent Running register func: <function Humidifier.handle_prefer_toggle at 0x7f9a881d90>
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.light.base_light
12/07/2022 17:44:15 INFO home_intent.home_intent Running register func: <function Light.handle_prefer_toggle at 0x7f9a81e400>
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.lock.base_lock
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.shopping_list.base_shopping_list
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.switch.base_switch
12/07/2022 17:44:15 INFO home_intent.home_intent Running register func: <function Switch.handle_prefer_toggle at 0x7f9a82c950>
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.weather.base_weather
12/07/2022 17:44:15 INFO home_intent.home_intent Running register func: <function Weather.handle_forecasting at 0x7f9a840488>
12/07/2022 17:44:15 INFO home_intent.home_intent Getting sentences for home_intent.components.home_assistant.media_player.base_media_player
12/07/2022 17:44:15 INFO home_intent.home_intent Updating all sentences in Rhasspy...
12/07/2022 17:44:16 INFO home_intent.home_intent Training Rhasspy... (can take up to 1m if many devices)
12/07/2022 17:44:16 ERROR root AttributeError: 'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "/usr/src/app/home_intent/__main__.py", line 64, in main
    home_intent.initialize()
  File "/usr/src/app/home_intent/home_intent.py", line 192, in initialize
    self._train()
  File "/usr/src/app/home_intent/home_intent.py", line 297, in _train
    self.rhasspy_api.post("/api/train", timeout=60)
  File "/usr/src/app/home_intent/rhasspy_api.py", line 47, in post
    raise RhasspyError(response.text)
home_intent.rhasspy_api.RhasspyError: AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by JarvyJ** [comment]
Oh wow, that's a full on Rhasspy Error. I'm going to merge in your latest PR with the typo fixes and look into the attribute error.

**Comment by JarvyJ** [comment]
Huh, well that was unexpected. The error was because one of the toggle light sentences started with a space. `" (allumer | éteindre) [la | le] [lumière] [de | du] ($light)",`. Also I think the volume set isn't working because Home Assistant probably wants a decimal instead of a comma. I still need to test it out though. I'll put in a PR here shortly with the fixes.

**Comment by JarvyJ** [comment]
Alright, I was finally able to cut the July release (the frontend build changing caused this to take a bit longer than I wanted), so now the French translation is now in latest! Thanks again for the translation efforts!
